[build-system]
requires = ["setuptools>=75", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "metrit"
dynamic = ["version"]
description = "A dead simple resources monitoring decorator"
authors = [{name = "Mario Crespo", email = "info@mariocrespo.es"}]
readme = "README.md"
dependencies = ["psutil==6.0.0", "multiprocess==0.70.17"]
requires-python = ">= 3.8"

license = {file = "LICENSE"}
classifiers = [
        "Development Status :: 4 - Beta",
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Intended Audience :: Developers",
    ]

[project.urls]
Repository = "https://github.com/mcrespoae/metrit"


[tool.setuptools_scm]
version_scheme = "guess-next-dev"
local_scheme = "no-local-version"
